name: Deploy to Yandex S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Yandex Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync . s3://${{ secrets.YC_BUCKET_NAME }}/ \
            --endpoint-url https://storage.yandexcloud.net \
            --region ru-central1 \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "package.json" \
            --exclude "*.md" \
            --no-progress
